### ISSUE TITLE
HS110 not working

### ISSUE THREAD

**Issue by pc-bastler** [kantlivelong/OctoPrint-PSUControl-TPLink#1]
#### What were you doing?

I am trying to switch a TP-Link HS110 via the OctoPrint Webinterface by the PSU-Control-Plugin.

1. I installed PSU Control and PSU Control TP-Link Plugins
2. I configured PSU Control to use the TP-Link-Plugin an set the Adress of my HS110 in the TP-Link-Plugin
3. I restarted OctoPrint
4. I tried to switch the Plug

My plug is a German HS110, FW. 1.5.4, HW 2.0

#### What did you expect to happen?

I expected to switch the Plug on and off. I also expected the Plugin to show the state of the Plug within the OctoPrint Webinterface (full and outline flash in the status bar).

#### What happened instead?

The plug does not switch on nor off. The Plugin shows the correct status in the statusbar when I switch the plug on and off by its app or any other method.

#### Version of OctoPrint-PSUControl

1.0.6

#### Version of OctoPrint-PSUControl-TPLink

1.0.1

#### Operating System running OctoPrint

Raspian, latest stable version

**Comment by kantlivelong** [comment]
Hi @pc-bastler,

Will need those DEBUG logs but I'm going to guess that either your OctoPrint install is unable to reach the device or it has been updated by TPLink to prevent the local communication.
