### ISSUE TITLE
KP115 not able to switch, state shown correctly

### ISSUE THREAD

**Issue by LXNDRGLN** [kantlivelong/OctoPrint-PSUControl-TPLink#3]
#### What did you expect to happen?
After installing and configuring the PSU plugin I expected to be able to toggle the state of the KP115 smartplug.

The hardware verison of the KP115 is 1.0 and firmware is 1.0.16.

Probably similar so Issue #1 
 
#### What happened instead?
Nothing happened, when I toggle the state in the TPLink KASA app, the state is shown corretly thow.

#### Version of OctoPrint-PSUControl
PSU Control (1.0.6)

#### Version of OctoPrint-PSUControl-TPLink
PSU Control - TPLink (1.0.1)

#### Operating System running OctoPrint

OctoPi Image (OctoPrint: 1.6.1 )

#### Attach or link DEBUG log files.

[octoprint.log](https://github.com/kantlivelong/OctoPrint-PSUControl-TPLink/files/7071001/octoprint.log)

**Comment by kantlivelong** [comment]
According to the log your Switching Method is set to GCODE. You need to set it to Plugin.

**Comment by LXNDRGLN** [comment]
Thanks for your help, I really just needed to set it to plugin.

In my mind I thought that the button in the top bar is always able to toggle the smart plug independent from the settings.
