### ISSUE TITLE
Wont turn of TPLink with a Prusa MK4

### ISSUE THREAD

**Issue by kevman28** [kantlivelong/OctoPrint-PSUControl-TPLink#8]
https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/issues/336

See issue above , looks like there are new temp commands and it get get idle state 

Recv: FIRMWARE_NAME:Prusa-Firmware-Buddy 5.0.0-ALPHA1+11007 (Github) SOURCE_CODE_URL:https://github.com/prusa3d/Prusa-Firmware-Buddy PROTOCOL_VERSION:1.0 MACHINE_TYPE:Prusa-mini EXTRUDER_COUNT:5 UUID:
Recv: Cap:SERIAL_XON_XOFF:0
Recv: Cap:BINARY_FILE_TRANSFER:0
Recv: Cap:EEPROM:0
Recv: Cap:VOLUMETRIC:1
Recv: Cap:AUTOREPORT_TEMP:1
Recv: Cap:PROGRESS:0
Recv: Cap:PRINT_JOB:1
Recv: Cap:AUTOLEVEL:1
Recv: Cap:Z_PROBE:1
Recv: Cap:LEVELING_DATA:1
Recv: Cap:BUILD_PERCENT:0
Recv: Cap:SOFTWARE_POWER:1
Recv: Cap:TOGGLE_LIGHTS:0
Recv: Cap:CASE_LIGHT_BRIGHTNESS:0
Recv: Cap:EMERGENCY_PARSER:0
Recv: Cap:PROMPT_SUPPORT:0
Recv: Cap:AUTOREPORT_SD_STATUS:0
Recv: Cap:THERMAL_PROTECTION:1
Recv: Cap:MOTION_MODES:0
Recv: Cap:CHAMBER_TEMPERATURE:0
Recv: ok
Recv: ok
Send: M155 S2
Recv: ok
Recv: T:25.00/0.00 B:24.49/0.00 X:24.72/36.00 A:26.51/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.49/0.00 X:24.70/36.00 A:26.64/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.55/0.00 X:24.72/36.00 A:26.80/0.00 @:0 B@:0 HBR@:0
Recv: T:25.19/0.00 B:24.61/0.00 X:24.70/36.00 A:26.98/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.61/0.00 X:24.73/36.00 A:27.16/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.55/0.00 X:24.72/36.00 A:27.19/0.00 @:0 B@:0 HBR@:0
Recv: T:25.09/0.00 B:24.55/0.00 X:24.71/36.00 A:27.45/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.61/0.00 X:24.74/36.00 A:27.50/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.49/0.00 X:24.71/36.00 A:27.60/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.37/0.00 X:24.71/36.00 A:27.71/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.40/0.00 X:24.70/36.00 A:27.97/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.43/0.00 X:24.70/36.00 A:28.02/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.55/0.00 X:24.71/36.00 A:28.07/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.61/0.00 X:24.72/36.00 A:28.10/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.58/0.00 X:24.74/36.00 A:28.23/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.58/0.00 X:24.72/36.00 A:28.39/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.52/0.00 X:24.72/36.00 A:28.52/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.52/0.00 X:24.72/36.00 A:28.57/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.55/0.00 X:24.71/36.00 A:28.72/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.55/0.00 X:24.71/36.00 A:28.80/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.55/0.00 X:24.71/36.00 A:28.83/0.00 @:0 B@:0 HBR@:0
Recv: T:25.09/0.00 B:24.58/0.00 X:24.74/36.00 A:28.96/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.67/0.00 X:24.72/36.00 A:29.01/0.00 @:0 B@:0 HBR@:0
Recv: T:25.75/0.00 B:24.58/0.00 X:24.73/36.00 A:29.19/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.61/0.00 X:24.73/36.00 A:29.11/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.61/0.00 X:24.73/36.00 A:29.22/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.52/0.00 X:24.74/36.00 A:29.27/0.00 @:0 B@:0 HBR@:0
Recv: T:25.09/0.00 B:24.43/0.00 X:24.73/36.00 A:29.43/0.00 @:0 B@:0 HBR@:0
Recv: T:25.09/0.00 B:24.61/0.00 X:24.74/36.00 A:29.51/0.00 @:0 B@:0 HBR@:0
Recv: T:26.22/0.00 B:24.64/0.00 X:24.73/36.00 A:29.56/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.61/0.00 X:24.73/36.00 A:29.66/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.61/0.00 X:24.73/36.00 A:29.66/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.67/0.00 X:24.74/36.00 A:29.79/0.00 @:0 B@:0 HBR@:0
Recv: T:25.47/0.00 B:24.49/0.00 X:24.73/36.00 A:29.84/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.52/0.00 X:24.74/36.00 A:29.92/0.00 @:0 B@:0 HBR@:0
Recv: T:25.09/0.00 B:24.52/0.00 X:24.74/36.00 A:29.95/0.00 @:0 B@:0 HBR@:0
Recv: T:25.47/0.00 B:24.64/0.00 X:24.75/36.00 A:30.04/0.00 @:0 B@:0 HBR@:0
Recv: T:25.47/0.00 B:24.55/0.00 X:24.73/36.00 A:30.04/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.55/0.00 X:24.73/36.00 A:30.02/0.00 @:0 B@:0 HBR@:0
Recv: T:25.19/0.00 B:24.55/0.00 X:24.74/36.00 A:30.17/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.55/0.00 X:24.70/36.00 A:30.15/0.00 @:0 B@:0 HBR@:0
Recv: T:25.19/0.00 B:24.49/0.00 X:24.72/36.00 A:30.21/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.52/0.00 X:24.73/36.00 A:30.27/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.58/0.00 X:24.75/36.00 A:30.31/0.00 @:0 B@:0 HBR@:0
Recv: T:25.56/0.00 B:24.58/0.00 X:24.75/36.00 A:30.40/0.00 @:0 B@:0 HBR@:0
Recv: T:25.00/0.00 B:24.58/0.00 X:24.73/36.00 A:30.35/0.00 @:0 B@:0 HBR@:0
Recv: T:25.75/0.00 B:24.52/0.00 X:24.73/36.00 A:30.44/0.00 @:0 B@:0 HBR@:0
Recv: T:26.03/0.00 B:24.52/0.00 X:24.74/36.00 A:30.48/0.00 @:0 B@:0 HBR@:0

**Comment by kantlivelong** [comment]
Hello,

Please fill out the template when submitting a ticket following all directions. Since this issue appears to affect the core plugin you can submit here instead: https://github.com/kantlivelong/OctoPrint-PSUControl/issues
